[package]
name = "dark-molecule-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
env_logger = "0.11.6"
diesel = { version = "2.2.0", features = ["postgres", "uuid", "chrono", "serde_json"] }
uuid = { version = "1.11.0" , features = ["v4", "fast-rng", "macro-diagnostics", "serde"]}
derive_more = { version = "1.0.0", features = ["full"] }
serde = { version = "1.0.215", features = ["derive"] }
chrono = { version = "0.4.39", features = ["serde"] }
