[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-session = { version = "0.10.1", features = ["cookie-session"] }
env_logger = "0.11.6"
diesel = { version = "2.2.0", features = ["postgres", "uuid", "chrono", "serde_json", "r2d2"] }
uuid = { version = "1.11.0" , features = ["v4", "fast-rng", "macro-diagnostics", "serde"]}
derive_more = { version = "2.0.1", features = ["full"] }
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.135"
chrono = { version = "0.4.39", features = ["serde"] }
log = "0.4.22"
dotenv = "0.15.0"
validator = { version = "0.20.0", features = ["derive"] }
argon2 = { version = "0.5.3", features = ["std"] }
rand = "0.9.0"
futures = "0.3.31"
listenfd = "1.0.2"
log4rs = "1.3.0"
utoipa-swagger-ui = { version = "9", features = ["actix-web"] }
handlebars = "6.3.1"
anyhow = "1.0.97"
time = "0.3.37"

[dev-dependencies]
dotenv = "0.15.0"
pretty_assertions = "1.4.1"
