[package]
name = "dark-molecule-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
env_logger = "0.11.6"
diesel = { version = "2.2.0", features = ["postgres", "uuid", "chrono"] }
uuid = { version = "1.11.0" , features = ["v4", "fast-rng", "macro-diagnostics", ]}
derive_more = { version = "1.0.0", features = ["full"] }
serde_json = "1.0"
log = "0.4.22"
dotenv = "0.15.0"
serde = { version = "1.0.215", features = ["derive"] }
chrono = "0.4.39"
